name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Window artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-2019
          repository: ceoifung/smart-arm
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
          path: build/
          
      - name: Download MacOS artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-11
          repository: ceoifung/smart-arm
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
          path: build/

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
