name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v2
        with:
          repository: ceoifung/smart-arm
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-2019
          path: build/
      - name: Download MacOS Artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-11
          path: build/
          
      - name: Unzip Packages
        run: |
          ls
          cd build
          unzip windows-2019.zip
          unzip macos-11.zip
          rm -rf *.zip
          ls
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
